### ISSUE TITLE
unable to download a single winload.efi

### ISSUE THREAD

**Issue by CR3Swapper** [m417z/winbindex#173]
Not sure what the deal is: https://winbindex.m417z.com/?file=winload.efi 

But im unable to download any winload.efi

**Comment by CR3Swapper** [comment]
nvm i found one from win10 1709

https://msdl.microsoft.com/download/symbols/winload.efi/5AA7603219a000/winload.efi

seems majority of the links are broken and return 404 tho...

**Comment by m417z** [comment]
Many efi files were removed by Microsoft about a year ago as a response to the BlackLotus UEFI bootkit:
https://twitter.com/m417z/status/1650393187960201218

**Comment by CR3Swapper** [comment]
> Many efi files were removed by Microsoft about a year ago as a response to the BlackLotus UEFI bootkit: https://twitter.com/m417z/status/1650393187960201218

ah makes sense, sad to see them go! Did they also remove the pdbs for all of these binaries? I was messing around with hyper-v highjacking a few years ago (https://github.com/backengineering/voyager) have those too been removed?

Anyways i was just looking to see if these EFI modules have an import directory in them for obfuscation purposes.

**Comment by m417z** [comment]
I don't know regarding pdbs and the other files, but it should be fairly straightforward to check.
