### ISSUE TITLE
Windows 11 Version 24H2

### ISSUE THREAD

**Issue by vrubleg** [m417z/winbindex#179]
Windows 11 Version 24H2 is in Release Preview and will become a release around this October. Its updates are already [published on the Microsoft Update Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=windows+11+24h2+security). It would be nice to support it.

**Comment by m417z** [comment]
I don't plan on adding preview versions to the main Winbindex dataset, but you can try the [Insider](https://winbindex.m417z.com/?arch=insider) dataset instead.

**Comment by vrubleg** [comment]
All the new laptops with Snapdragon X Elite are already shipped with the Windows 11 24H2 so it's released at least for ARM64. The x86-64 version is also ready, just waiting to be pushed to everybody.

Anyway, the Insider dataset works for me, thanks.

**Comment by m417z** [comment]
Yesterday Microsoft updated the support pages (which the Winbindex scripts use) with all the 24H2 updates:
https://support.microsoft.com/en-us/help/5045988
They're now indexed and available.

I also updated the database with files from the 24H2 ISO files.
