### ISSUE TITLE
Windows 1909 is missing

### ISSUE THREAD

**Issue by westyles** [m417z/winbindex#2]
Cool, but Windows 1909 is missing from the download list!

**Comment by m417z** [comment]
It's missing because it shares the same updates as Windows 10 1903. From [Windows Help](https://support.microsoft.com/en-ie/help/4529964):

> Windows 10, versions 1903 and 1909 share a common core operating system and an identical set of system files. As a result, the new features in Windows 10, version 1909 were included in the recent monthly quality update for Windows 10, version 1903 (released October 8, 2019), but are currently in a dormant state. These new features will remain dormant until they are turned on using an enablement package, which is a small, quick-to-install “master switch” that simply activates the Windows 10, version 1909 features.

**Comment by m417z** [comment]
I figured that it will be less confusing and more useful to mark those files as part of both 1903 and 1909, especially after I added the ISO files data and it became inconsistent. Now done in https://github.com/m417z/winbindex/commit/317765fa05863b33930d5ecfe719f328be6d4f20.
